tiles.setCurrentTilemap(tilemap`level1`)
let mySprite = sprites.create(assets.image`myImage`, SpriteKind.Player)
scene.cameraFollowSprite(mySprite)
controller.moveSprite(mySprite)
let my_Enemy = sprites.create(assets.image`myImage0`, SpriteKind.Enemy)
my_Enemy.follow(mySprite)
